name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Debug SVG Generation
        run: |
          ls -la dist/ || echo "dist/ directory not found"
          if [ -f dist/snake.svg ]; then
            echo "snake.svg exists, contents:"
            cat dist/snake.svg
          else
            echo "Error: snake.svg was not generated!"
            exit 1
          fi

      - name: Customize Snake SVG
        run: |
          # Ensure dist/ is writable
          chmod -R u+w dist/
          # Modify SVG by piping to a temp file and replacing
          sed 's|<svg width="\(.*\)" height="\(.*\)"|<svg width="\1" height="\2" style="background-color: #1a1a1a;|' dist/snake.svg > dist/snake_temp.svg
          mv dist/snake_temp.svg dist/snake.svg
          # Optional: Change snake color (adjust after inspecting default)
          sed -i 's/fill="#00ff00"/fill="#ff5555"/g' dist/snake.svg

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
